### ISSUE TITLE
Can't add more than one instance per page.

### ISSUE THREAD

**Issue by raphaelkross** [terwanerik/FadeShow#2]
Hey - first of all, thank you for the plugin - it works really nicely 👍 

The plugin works perfectly, but using IDs and counts (0, 1, 2, ...) makes this inflexible - for example, if you run more than one instance per page, it'll break - because two IDs fadeShow-slide0 will be created.

I modified the code a bit to use classes and point to elements inside the container, instead looking globally. This way, we can have as many instances as we want inside one page.

PS.: I didn't have the time to compile the minified versions, sorry for that!

PS2.: I already sent a fix for this issue - just merge it and generate the new compiled files 😄

**Comment by terwanerik** [comment]
Thanks for the PR!
