### ISSUE TITLE
Can we include arrows?

### ISSUE THREAD

**Issue by TenSketch** [terwanerik/FadeShow#4]
Can we include left and right arrows

**Comment by terwanerik** [comment]
This project is very old, and unmaintained. You might be able to build it in yourself, but needs some refactoring. Checkout the [nextImage](https://github.com/terwanerik/FadeShow/blob/master/src/jquery.fadeshow-0.1.2.js#L104) function, might help you along.

Please mind that you would have to also include a `previousImage` function, and probably stop / clear the interval upon user interaction.

**Comment by terwanerik** [comment]
Pull requests are welcome! :)

**Comment by TenSketch** [comment]
OKay thank you
